import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import { LinearProgress } from "@mui/material";
import GlobalSnackbar from "@/components/GlobalSnackbar";
import Providers from "@/lib/Providers";

export const metadata: Metadata = {
  title: "ERP-System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Providers>
          <Suspense fallback={<LinearProgress />}> {children} </Suspense>
          <GlobalSnackbar />
        </Providers>
      </body>
    </html>
  );
}
